config/routes.rb
Rails.application.routes.draw do
  resources :rodents
  root 'dashboard#show'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/rodent.rb
class Rodent < ApplicationRecord
  validates_presence_of :name
  after_commit :update_rodents_counter

  private

  def update_rodents_counter
    broadcast_replace_later_to :dashboard, target: 'rodents-counter', partial: 'dashboard/rodents_counter', locals: {rodent: nil}
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def show
  end
end

app/controllers/rodents_controller.rb
class RodentsController < ApplicationController
  before_action :set_rodent, only: %i[ show edit update destroy ]

  # GET /rodents
  def index
    @rodents = Rodent.all
  end

  # GET /rodents/1
  def show
  end

  # GET /rodents/new
  def new
    @rodent = Rodent.new
  end

  # GET /rodents/1/edit
  def edit
  end

  # POST /rodents
  def create
    @rodent = Rodent.new(rodent_params)

    if @rodent.save
      redirect_to @rodent, notice: "Rodent was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /rodents/1
  def update
    if @rodent.update(rodent_params)
      redirect_to @rodent, notice: "Rodent was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /rodents/1
  def destroy
    @rodent.destroy
    redirect_to rodents_url, notice: "Rodent was successfully destroyed.", status: :see_other
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rodent
      @rodent = Rodent.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def rodent_params
      params.require(:rodent).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/dashboard/_counter.html.slim
p#rodents-counter There are #{Rodent.count} rodents in the encyclopedia!

app/views/dashboard/_rodents_counter.html.slim
p#rodents-counter There are #{Rodent.count} rodents in the encyclopedia!

app/views/dashboard/show.html.slim
= turbo_stream_from :dashboard

h1 Dashboard

== render 'rodents_counter'

p = link_to 'The Rodents', rodents_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>The Rodents Encyclopedia</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/rodents/_form.html.slim
= form_for @rodent do |f|
  - if @rodent.errors.any?
    #error_explanation
      h2 = "#{pluralize(@rodent.errors.count, 'error')} prohibited this rodent from being saved:"
      ul
        - @rodent.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :name
    br
    = f.text_field :name

  .actions
    = f.submit

app/views/rodents/edit.html.slim
h1 Editing rodent

== render 'form'

p
  => link_to 'Show', @rodent
  '|
  =< link_to 'Back', rodents_path

app/views/rodents/index.html.slim
h1 Listing rodents

table
  thead
    tr
      th Name
      th
      th
      th

  tbody
    - @rodents.each do |rodent|
      tr
        td = rodent.name
        td = link_to 'Show', rodent
        td = link_to 'Edit', edit_rodent_path(rodent)
        td = link_to 'Destroy', rodent, data: { turbo_confirm: 'Are you sure?', turbo_method: :delete }

br

p = link_to 'New Rodent', new_rodent_path
p = link_to 'Back to dashboard', root_path

app/views/rodents/new.html.slim
h1 New rodent

== render 'form'

= link_to 'Back', rodents_path

app/views/rodents/show.html.slim
p#notice = notice

p
  strong Name:
  =< @rodent.name

p
  => link_to 'Edit', edit_rodent_path(@rodent)
  '|
  =< link_to 'Back', rodents_path